// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // iOS Firebase values are intentionally not guessed here.
        // If ios/Runner/GoogleService-Info.plist exists, regenerate this file
        // with `flutterfire configure` so the Dart options and plist match.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'run `flutterfire configure` and commit the regenerated options.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJDV3pMxpZs5Suo3oYCQsOUnKG7uY-I8',
    appId: '1:615117501330:web:6c62b53fd63825a879074b',
    messagingSenderId: '615117501330',
    projectId: 'salati-cf0db',
    authDomain: 'salati-cf0db.firebaseapp.com',
    storageBucket: 'salati-cf0db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfPhzMLAGKhXS1q8H6IFBdw2gDTNcdZk',
    appId: '1:615117501330:android:8f54d978fc21856579074b',
    messagingSenderId: '615117501330',
    projectId: 'salati-cf0db',
    storageBucket: 'salati-cf0db.firebasestorage.app',
  );
}
