import 'package:flutter/widgets.dart';

class SalatiLocalizations {
  const SalatiLocalizations(this.languageCode);

  final String languageCode;

  static SalatiLocalizations of(BuildContext context) {
    return SalatiLocalizations(Localizations.localeOf(context).languageCode);
  }

  String text(String key) {
    final table = _localizedValues[languageCode] ?? _localizedValues['ar']!;
    return table[key] ?? _localizedValues['ar']![key] ?? key;
  }
}

const _localizedValues = <String, Map<String, String>>{
  'ar': {
    'appName': 'صلاتي',
    'adhkar': 'الأذكار',
    'quran': 'القرآن',
    'salati': 'صلاتي',
    'duas': 'الأدعية',
    'profile': 'الملف',
    'sessionPreparing': 'جار تجهيز الجلسة',
    'freeAccount': 'حساب مجاني',
    'linkedAccount': 'حساب مرتبط',
    'subscription': 'الاشتراك',
    'store': 'المتجر',
    'prayerSettings': 'إعدادات الصلاة',
    'appearanceFonts': 'المظهر والخطوط',
    'darkMode': 'الوضع الداكن',
    'darkModeSubtitle': 'بدل المظهر بما يناسبك',
    'language': 'اللغة',
    'languagePickerLabel': 'لغة التطبيق وترجمة القرآن',
    'loginOrLink': 'تسجيل الدخول أو ربط الحساب',
    'logout': 'تسجيل الخروج',
  },
  'en': {
    'appName': 'Salati',
    'adhkar': 'Adhkar',
    'quran': 'Quran',
    'salati': 'Salati',
    'duas': 'Duas',
    'profile': 'Profile',
    'sessionPreparing': 'Preparing session',
    'freeAccount': 'Free account',
    'linkedAccount': 'Linked account',
    'subscription': 'Subscription',
    'store': 'Store',
    'prayerSettings': 'Prayer settings',
    'appearanceFonts': 'Appearance and fonts',
    'darkMode': 'Dark mode',
    'darkModeSubtitle': 'Switch the look to suit you',
    'language': 'Language',
    'languagePickerLabel': 'App language and Quran translation',
    'loginOrLink': 'Sign in or link account',
    'logout': 'Sign out',
  },
  'fr': {
    'appName': 'Salati',
    'adhkar': 'Adhkar',
    'quran': 'Coran',
    'salati': 'Salati',
    'duas': 'Invocations',
    'profile': 'Profil',
    'sessionPreparing': 'Préparation de la session',
    'freeAccount': 'Compte gratuit',
    'linkedAccount': 'Compte lié',
    'subscription': 'Abonnement',
    'store': 'Boutique',
    'prayerSettings': 'Paramètres de prière',
    'appearanceFonts': 'Apparence et polices',
    'darkMode': 'Mode sombre',
    'darkModeSubtitle': 'Adaptez l’apparence à vos préférences',
    'language': 'Langue',
    'languagePickerLabel': 'Langue de l’application et traduction du Coran',
    'loginOrLink': 'Se connecter ou lier le compte',
    'logout': 'Se déconnecter',
  },
  'es': {
    'appName': 'Salati',
    'adhkar': 'Adhkar',
    'quran': 'Corán',
    'salati': 'Salati',
    'duas': 'Súplicas',
    'profile': 'Perfil',
    'sessionPreparing': 'Preparando sesión',
    'freeAccount': 'Cuenta gratis',
    'linkedAccount': 'Cuenta vinculada',
    'subscription': 'Suscripción',
    'store': 'Tienda',
    'prayerSettings': 'Ajustes de oración',
    'appearanceFonts': 'Apariencia y fuentes',
    'darkMode': 'Modo oscuro',
    'darkModeSubtitle': 'Cambia el aspecto como prefieras',
    'language': 'Idioma',
    'languagePickerLabel': 'Idioma de la app y traducción del Corán',
    'loginOrLink': 'Iniciar sesión o vincular cuenta',
    'logout': 'Cerrar sesión',
  },
  'de': {
    'appName': 'Salati',
    'adhkar': 'Adhkar',
    'quran': 'Koran',
    'salati': 'Salati',
    'duas': 'Bittgebete',
    'profile': 'Profil',
    'sessionPreparing': 'Sitzung wird vorbereitet',
    'freeAccount': 'Kostenloses Konto',
    'linkedAccount': 'Verknüpftes Konto',
    'subscription': 'Abo',
    'store': 'Store',
    'prayerSettings': 'Gebetseinstellungen',
    'appearanceFonts': 'Design und Schriften',
    'darkMode': 'Dunkelmodus',
    'darkModeSubtitle': 'Passe das Aussehen an',
    'language': 'Sprache',
    'languagePickerLabel': 'App-Sprache und Koranübersetzung',
    'loginOrLink': 'Anmelden oder Konto verknüpfen',
    'logout': 'Abmelden',
  },
  'id': {
    'appName': 'Salati',
    'adhkar': 'Zikir',
    'quran': 'Quran',
    'salati': 'Salati',
    'duas': 'Doa',
    'profile': 'Profil',
    'sessionPreparing': 'Menyiapkan sesi',
    'freeAccount': 'Akun gratis',
    'linkedAccount': 'Akun tertaut',
    'subscription': 'Langganan',
    'store': 'Toko',
    'prayerSettings': 'Pengaturan salat',
    'appearanceFonts': 'Tampilan dan font',
    'darkMode': 'Mode gelap',
    'darkModeSubtitle': 'Ubah tampilan sesuai pilihanmu',
    'language': 'Bahasa',
    'languagePickerLabel': 'Bahasa app dan terjemahan Quran',
    'loginOrLink': 'Masuk atau tautkan akun',
    'logout': 'Keluar',
  },
  'tr': {
    'appName': 'Salati',
    'adhkar': 'Zikirler',
    'quran': 'Kur’an',
    'salati': 'Salati',
    'duas': 'Dualar',
    'profile': 'Profil',
    'sessionPreparing': 'Oturum hazırlanıyor',
    'freeAccount': 'Ücretsiz hesap',
    'linkedAccount': 'Bağlı hesap',
    'subscription': 'Abonelik',
    'store': 'Mağaza',
    'prayerSettings': 'Namaz ayarları',
    'appearanceFonts': 'Görünüm ve yazı tipleri',
    'darkMode': 'Koyu mod',
    'darkModeSubtitle': 'Görünümü sana uygun değiştir',
    'language': 'Dil',
    'languagePickerLabel': 'Uygulama dili ve Kur’an çevirisi',
    'loginOrLink': 'Giriş yap veya hesabı bağla',
    'logout': 'Çıkış yap',
  },
  'ur': {
    'appName': 'صلاتی',
    'adhkar': 'اذکار',
    'quran': 'قرآن',
    'salati': 'صلاتی',
    'duas': 'دعائیں',
    'profile': 'پروفائل',
    'sessionPreparing': 'سیشن تیار ہو رہا ہے',
    'freeAccount': 'مفت اکاؤنٹ',
    'linkedAccount': 'منسلک اکاؤنٹ',
    'subscription': 'سبسکرپشن',
    'store': 'اسٹور',
    'prayerSettings': 'نماز کی ترتیبات',
    'appearanceFonts': 'ظاہری شکل اور فونٹس',
    'darkMode': 'ڈارک موڈ',
    'darkModeSubtitle': 'اپنی پسند کے مطابق شکل بدلیں',
    'language': 'زبان',
    'languagePickerLabel': 'ایپ کی زبان اور قرآن ترجمہ',
    'loginOrLink': 'لاگ ان یا اکاؤنٹ لنک کریں',
    'logout': 'لاگ آؤٹ',
  },
};
